#!/usr/bin/env bash

set -x

# ====== Variables =============================

declare -A gaps
declare -A color

gaps["top"]="20"
gaps["bottom"]="20"
gaps["left"]="20"
gaps["right"]="20"
gaps["inner"]="20"

color["focused"]="0xE0808080"
color["normal"]="0x00010101"
color["preselect"]="0xE02d74da"

# Uncomment to refresh ubersicht widget on workspace change
# Make sure to replace WIDGET NAME for the name of the ubersicht widget
#ubersicht_spaces_refresh_command="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"WIDGET NAME\"'"

# ===== Loading Scripting Additions ============

# See: https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#macos-big-sur---automatically-load-scripting-addition-on-startup
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# ===== Tiling setting =========================

yabai -m config layout bsp

yabai -m config top_padding "${gaps["top"]}"
yabai -m config bottom_padding "${gaps["bottom"]}"
yabai -m config left_padding "${gaps["left"]}"
yabai -m config right_padding "${gaps["right"]}"
yabai -m config window_gap "${gaps["inner"]}"

yabai -m config mouse_follows_focus on
yabai -m config focus_follows_mouse autofocus

yabai -m config window_topmost off
yabai -m config window_opacity on
yabai -m config window_shadow float

yabai -m config window_border on
yabai -m config window_border_width 8

yabai -m config active_window_border_color 0xFFe78a4e # Gruvbox orange
yabai -m config normal_window_border_color 0xFF665c54 # Gruvbox dark gray
yabai -m config insert_feedback_color 0xFFea6962

yabai -m config active_window_opacity 0.7
yabai -m config normal_window_opacity 0.7
yabai -m window --opacity 0.7
yabai -m config split_ratio 0.50

yabai -m config auto_balance off

yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize

yabai -m config window_border_blur off

set +x
printf "yabai: configuration loaded...\\n"
borders active_color=0xffb8bb26 inactive_color=0xff665c54 width=12.0 &
